'use client';

import React from 'react';

interface PdfRendererProps {
  url?: string;
  title?: string;
}

export default function PdfRenderer({ url, title }: PdfRendererProps) {
  const pdfTitle = title || 'PDF Document Deliverable';
  const pdfUrl = url || '#';

  return (
    <div className="bg-[#121216] border border-zinc-800 rounded-xl overflow-hidden shadow-lg my-2.5">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-2.5 bg-[#17171d] border-b border-zinc-800/80">
        <div className="flex items-center gap-2">
          <div className="w-5 h-5 rounded bg-red-500/20 text-red-400 flex items-center justify-center text-xs font-bold">
            📄
          </div>
          <span className="font-medium text-xs text-zinc-100">{pdfTitle}</span>
          <span className="text-[10px] text-zinc-500 font-mono uppercase px-1.5 py-0.5 bg-zinc-800/70 rounded">
            PDF
          </span>
        </div>

        <div className="flex items-center gap-2">
          <a
            href={pdfUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-1 px-2.5 py-1 rounded bg-zinc-800 hover:bg-zinc-700 text-zinc-200 hover:text-white text-xs font-medium transition-colors"
          >
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
            </svg>
            <span>Open PDF</span>
          </a>
          <a
            href={pdfUrl}
            download
            className="flex items-center gap-1 px-2.5 py-1 rounded bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-medium transition-colors shadow-sm"
          >
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            <span>Download</span>
          </a>
        </div>
      </div>

      {/* Embedded View / Placeholder */}
      <div className="p-4 bg-black/40">
        {url && url.startsWith('http') ? (
          <iframe
            src={url}
            title={pdfTitle}
            className="w-full h-96 rounded border border-zinc-800"
          />
        ) : (
          <div className="flex flex-col items-center justify-center py-10 text-center space-y-3">
            <div className="w-12 h-12 rounded-full bg-red-500/10 text-red-400 flex items-center justify-center text-xl">
              📑
            </div>
            <div>
              <p className="text-xs font-medium text-zinc-200">{pdfTitle}</p>
              <p className="text-[11px] text-zinc-500 mt-0.5">PDF artifact generated by agent task execution</p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
